version: '3.8'

services:
  api:
    container_name: ${PROJECT_NAME}-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
    env_file: .env
    restart: unless-stopped
    ports:
      - ${DOMAIN_PORT}:${PORT}
    networks:
      - nestapp

  prod-db:
    image: mysql
    container_name: ${PROJECT_NAME}-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:3306
    networks:
      - nestapp
    volumes:
      - nestapp:/var/lib/mysql

networks:
  nestapp:


volumes:
  nestapp:
